source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'BeeKit_Example' do

    # 必备组件
    pod 'BeeKit-Swift', :path => '../'

    # 必备组件
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RxWebKit'
    pod 'RxGesture'
    pod 'RxReachability'
    pod 'RxViewController'

    # UI
    pod 'SnapKit'
    pod 'PinLayout'
    pod 'BEEPopupKit'
    pod 'BEEFormKit'
    pod 'BEETableKit'

    # Networking
    pod 'BEENetwork'
    pod 'Kingfisher'

    # 自定义动图加载
    pod 'lottie-ios'

    # 存储
#    pod 'WCDB.swift'
#    pod 'KeychainAccess'

    # UI
  #  pod 'IBPCollectionViewCompositionalLayout'
  #  pod 'DiffableDataSources'
  #  pod 'YYText'
  #  pod 'AMPopTip'
  #  pod 'JXSegmentedView'
  #  pod 'JXPagingView'
  #  pod 'JXPhotoBrowser'
  #  pod 'Lantern'
  #  pod 'FSPagerView'
  #  pod 'EBBannerView'
  #  pod 'BRPickerView'
  #  pod 'SwipeCellKit'
  #  pod 'FSCalendar'
  #  pod 'FloatingPanel'
  #  pod 'SkeletonView'
  #  pod 'Hero'
  #  pod 'FFPopup'

    # 工具
    pod 'Device'
    pod 'PermissionKit'
    pod 'IQKeyboardManagerSwift'
    pod 'R.swift'

    # 社会化分享 && 支付
    pod 'MonkeyKing'

    # 自定义动图加载
#    pod 'lottie-ios'

    # Misc.
#    pod 'Transporter' # StateMachine

    # Debug
    pod 'LookinServer', :configurations => ['Debug']
    pod 'DoraemonKit/Core', :git => "https://gitee.com/yixiangboy/DoraemonKit.git", :tag => '3.0.2', :configurations => ['Debug'] #必选
    pod 'DoraemonKit/WithLogger', :git => "https://gitee.com/yixiangboy/DoraemonKit.git", :tag => '3.0.2', :configurations => ['Debug'] #可选
    pod 'DoraemonKit/WithMLeaksFinder', :git => "https://gitee.com/yixiangboy/DoraemonKit.git", :tag => '3.0.2', :configurations => ['Debug'] #可选

  target 'BeeKit_Tests' do
    inherit! :search_paths

  end
end
