source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.0'

target 'BeeKit_Example' do
    pod 'BeeKit', :path => '../'

    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RxWebKit'

    pod 'SnapKit'
    pod 'PinLayout'

    pod 'BEEPopupKit'
    pod 'BEEFormKit'
    pod 'BEETableKit'
    pod 'BEENetwork'
    pod 'PermissionKit'

    # Debug
    pod 'DoraemonKit/Core', :git => "https://gitee.com/yixiangboy/DoraemonKit.git", :tag => '3.0.2', :configurations => ['Debug'] #必选
    pod 'DoraemonKit/WithLogger', :git => "https://gitee.com/yixiangboy/DoraemonKit.git", :tag => '3.0.2', :configurations => ['Debug'] #可选
    pod 'DoraemonKit/WithMLeaksFinder', :git => "https://gitee.com/yixiangboy/DoraemonKit.git", :tag => '3.0.2', :configurations => ['Debug'] #可选

  target 'BeeKit_Tests' do
    inherit! :search_paths

  end
end
